import tw from 'twin.macro';
import Head from '@components/core/Head';
import { Inter } from 'next/font/google';
import GlobalStyles from '@styles/GlobalStyles';

//######################### COMPONENT TYPES ################################################
type Props = {
  children: React.ReactNode;
};

//######################### COMPONENT META #################################################
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//######################### COMPONENT STYLES ###############################################
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

// const HTML = tw.html`antialiased`;

// const Body = tw.body``;

//######################### COMPONENT ######################################################
function RootLayout({ children }: Props) {
  return (
    <html lang='en' className={`${inter.variable} font-sans`}>
      <Head />
      {/* <GlobalStyles /> */}
      <body>{children}</body>
    </html>
  );
}

export default RootLayout;
